"""Domain enums for the AI Intelligence Engine module."""

from __future__ import annotations

import enum


class RiskLevel(str, enum.Enum):
    """Overall risk classification for a venue or zone assessment."""

    GREEN = "green"
    YELLOW = "yellow"
    ORANGE = "orange"
    RED = "red"
    CRITICAL = "critical"


class PredictionType(str, enum.Enum):
    """Category of predictive analytics generated by the intelligence engine."""

    BOTTLENECK = "bottleneck"
    CONGESTION = "congestion"
    QUEUE_GROWTH = "queue_growth"
    DANGEROUS_DENSITY = "dangerous_density"
    MEDICAL_OVERLOAD = "medical_overload"
    VOLUNTEER_SHORTAGE = "volunteer_shortage"
    EXIT_SATURATION = "exit_saturation"
    TRANSPORT_CONGESTION = "transport_congestion"
    WHEELCHAIR_BLOCKAGE = "wheelchair_blockage"
    LOST_CHILD = "lost_child"
    CLEANING_OVERLOAD = "cleaning_overload"
    SECURITY_PRESSURE = "security_pressure"


class DecisionStatus(str, enum.Enum):
    """Lifecycle state of an autonomous intervention decision."""

    CANDIDATE = "candidate"
    SIMULATED = "simulated"
    SELECTED = "selected"
    PUBLISHED = "published"
    EXECUTED = "executed"
    REJECTED = "rejected"
    EXPIRED = "expired"


class InterventionType(str, enum.Enum):
    """Type of operational intervention the AI can recommend or execute."""

    DO_NOTHING = "do_nothing"
    REDIRECT_VOLUNTEERS = "redirect_volunteers"
    OPEN_SECONDARY_GATE = "open_secondary_gate"
    DEPLOY_MEDICAL = "deploy_medical"
    CLOSE_CORRIDOR = "close_corridor"
    REVERSE_FLOW = "reverse_flow"
    SPLIT_CROWD = "split_crowd"
    MULTILINGUAL_ANNOUNCEMENT = "multilingual_announcement"
    INCREASE_SECURITY = "increase_security"
    ACCESSIBILITY_PRIORITY_ROUTING = "accessibility_priority_routing"


class MatchPhase(str, enum.Enum):
    """Temporal phase of a match lifecycle for context-aware decisions."""

    PRE_MATCH = "pre_match"
    KICKOFF = "kickoff"
    FIRST_HALF = "first_half"
    HALFTIME = "halftime"
    SECOND_HALF = "second_half"
    EXTRA_TIME = "extra_time"
    PENALTY_SHOOTOUT = "penalty_shootout"
    POST_MATCH = "post_match"
    RAIN_DELAY = "rain_delay"
    EVACUATION = "evacuation"


class ConfidenceSource(str, enum.Enum):
    """Individual factors that contribute to an overall confidence score."""

    SENSOR_AGREEMENT = "sensor_agreement"
    HISTORICAL_SIMILARITY = "historical_similarity"
    MODEL_AGREEMENT = "model_agreement"
    DATA_FRESHNESS = "data_freshness"
    EVIDENCE_COUNT = "evidence_count"


class ObservationType(str, enum.Enum):
    """Source classification for observations feeding the intelligence engine."""

    REALTIME = "realtime"
    REPLAY = "replay"
    SIMULATION = "simulation"
