"""Entity type enumeration for all stadium objects."""

from __future__ import annotations

import enum


class EntityType(str, enum.Enum):
    """Every physical object in the stadium becomes one of these entity types."""

    GATE = "gate"
    ENTRANCE = "entrance"
    EXIT = "exit"
    ZONE = "zone"
    CONCOURSE = "concourse"
    CORRIDOR = "corridor"
    ESCALATOR = "escalator"
    ELEVATOR = "elevator"
    RAMP = "ramp"
    STAIRCASE = "staircase"
    RESTROOM = "restroom"
    MEDICAL_ROOM = "medical_room"
    FOOD_COURT = "food_court"
    VENDOR = "vendor"
    SECURITY_CHECKPOINT = "security_checkpoint"
    PARKING_AREA = "parking_area"
    METRO_STATION = "metro_station"
    BUS_STOP = "bus_stop"
    SHUTTLE_POINT = "shuttle_point"
    CAMERA = "camera"
    IOT_SENSOR = "iot_sensor"
    VOLUNTEER_POSITION = "volunteer_position"
    CROWD_CLUSTER = "crowd_cluster"
    EMERGENCY_EXIT = "emergency_exit"
    FIRE_EXTINGUISHER = "fire_extinguisher"
    AED = "aed"
    WHEELCHAIR_STATION = "wheelchair_station"
    CLEANING_BIN = "cleaning_bin"
    CHARGING_STATION = "charging_station"
    LOST_AND_FOUND = "lost_and_found"
    INFORMATION_DESK = "information_desk"
    SEATING_BLOCK = "seating_block"
    SEATING_ROW = "seating_row"
    SEAT = "seat"
    CONCESSION_STAND = "concession_stand"
    FIRST_AID_POST = "first_aid_post"
    COMMAND_CENTER = "command_center"
    PRESS_BOX = "press_box"
    VIP_LOUNGE = "vip_lounge"
    LUXURY_BOX = "luxury_box"
    FIELD = "field"
    STAGE = "stage"
    BARRIER = "barrier"
    SIGNAGE = "signage"
    LIGHTING = "lighting"
    SPEAKER = "speaker"
    DISPLAY_SCREEN = "display_screen"
    WATER_FOUNTAIN = "water_fountain"
    WIFI_ACCESS_POINT = "wifi_access_point"
